
auth.token=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

defaults.org=gilead-technologies
defaults.project=react-native

defaults.url=https://sentry.io/
